// NAXA — contenu multilingue centralisé (source unique de vérité du texte du site).
// Structure : t[lang].<section>. Les templates bouclent sur ces données.
// FR = référence. EN/AR ajoutés ensuite (AR à relire par un humain avant prod).

const techBadges = [
  "Llama 3", "Mistral", "Qwen", "Ollama", "vLLM", "LangChain", "LlamaIndex",
  "n8n", "Make", "Supabase", "PostgreSQL", "Qdrant", "Weaviate", "Docker",
  "FastAPI", "Next.js", "WhatsApp Cloud API", "Twilio",
];

const fr = {
  techBadges,
  ui: {
    skip: "Aller au contenu principal",
    logoAlt: "NAXA",
    menu: "Menu",
    langGroup: "Langue / Language / اللغة",
    whatsappFab: "Contactez-nous sur WhatsApp",
    verified: "Vérifié",
    verifiedTitle: "Client vérifié",
    ratingLabel: "Note : 5 sur 5",
  },
  nav: {
    home: "Accueil", services: "Services", solutions: "Solutions IA",
    about: "À propos", contact: "Contact", cta: "Démarrer un projet",
  },
  footer: {
    brand: "Agence digitale spécialisée en IA locale, automatisation métier et chatbots intelligents. Basée au Maroc, au service d'entreprises ambitieuses.",
    colServices: "Services", colCompany: "Entreprise", colContact: "Contact",
    servicesLinks: ["IA locale", "Automatisation", "Chatbots", "Création digitale"],
    location: "Maroc",
    copy: "© 2026 NAXA — Tous droits réservés.",
    tagline: "IA locale · Souveraineté des données",
  },
  meta: {
    home: {
      title: "NAXA — IA locale, automatisation & chatbots pour entreprises",
      desc: "Agence IA Maroc — NAXA déploie de l'Intelligence Artificielle locale, automatisation métier et chatbots WhatsApp pour entreprises à Casablanca, Rabat, Marrakech et Tanger. Souveraineté des données, ROI mesurable.",
    },
    services: {
      title: "Services — NAXA · IA locale, automatisation, chatbots",
      desc: "Découvrez les services NAXA : intelligence artificielle locale, automatisation des workflows, chatbots WhatsApp et web, création digitale.",
    },
    solutions: {
      title: "Solutions IA — NAXA · Cas d'usage métiers",
      desc: "Solutions IA NAXA par cas d'usage : assistant documentaire, OCR factures, chatbot WhatsApp, automatisation comptable, vision industrielle.",
    },
    about: {
      title: "À propos — NAXA · L'agence IA locale & automatisation",
      desc: "NAXA, agence digitale marocaine spécialisée en IA locale et automatisation. Notre vision, nos valeurs, notre équipe.",
    },
    contact: {
      title: "Contact — NAXA · Démarrons votre projet IA",
      desc: "Contactez NAXA pour discuter de votre projet d'IA locale, automatisation ou chatbot. Audit gratuit, réponse sous 24h.",
    },
    merci: {
      title: "Merci — NAXA",
      desc: "Votre demande a bien été reçue. Notre équipe revient vers vous sous 24h.",
    },
    nf: {
      title: "Page introuvable (404) — NAXA",
      desc: "La page demandée est introuvable. Retournez à l'accueil NAXA ou contactez-nous.",
    },
  },
  home: {
    hero: {
      tag: "IA locale · Automatisation · Chatbots",
      titleHtml: `Vos processus, <span class="text-grad">augmentés par l'IA</span><br>sans jamais perdre vos données.`,
      subHtml: `NAXA conçoit et déploie des solutions d'<strong>Intelligence Artificielle locale</strong>, d'automatisation métier et de chatbots qui s'intègrent à votre activité — souveraineté totale, ROI mesurable, et un accompagnement humain à chaque étape.`,
      ctaAudit: "Audit gratuit ›",
      ctaSolutions: "Découvrir nos solutions",
      trust: ["Données 100% on-premise", "Modèles open-source", "Conformité RGPD / Loi 09-08"],
    },
    stats: [
      { num: 40, suffix: "+", label: "Projets déployés" },
      { num: 70, suffix: "%", label: "Tâches répétitives automatisées" },
      { num: 24, suffix: "/7", label: "Disponibilité chatbot" },
      { num: 100, suffix: "%", label: "Données souveraines" },
    ],
    services: {
      tag: "Nos expertises",
      titleHtml: `Trois piliers, une mission : <span class="text-grad">libérer votre productivité</span>`,
      intro: "De l'IA déployée sur vos serveurs à l'automatisation de vos workflows en passant par des chatbots intelligents — tout, intégré nativement à vos outils.",
      cards: [
        { icon: "⚡", title: "Intelligence Artificielle locale", desc: "Déploiement de modèles LLM open-source (Llama, Mistral, Qwen) directement sur votre infrastructure. Vos données ne quittent jamais vos serveurs.", list: ["RAG sur documents internes", "Assistants métier sur-mesure", "Vision IA & OCR avancé", "Fine-tuning sectoriel"] },
        { icon: "⚙", title: "Automatisation métier", desc: "Connectez vos outils (CRM, ERP, mails, comptabilité) et laissez les workflows tourner seuls. Gain de temps immédiat, erreurs humaines éliminées.", list: ["n8n, Make, Zapier auto-hébergés", "Intégrations API sur-mesure", "Reporting & dashboards auto", "Process RH, finance, logistique"] },
        { icon: "💬", title: "Chatbots intelligents", desc: "Chatbots WhatsApp, web et Messenger boostés à l'IA, capables de comprendre, qualifier et convertir 24h/24, en français, arabe et darija.", list: ["WhatsApp Business API", "Support client multilingue", "Qualification de leads", "Connexion CRM & paiement"] },
      ],
    },
    sectors: {
      tag: "Secteurs",
      titleHtml: `Une expertise <span class="text-grad">adaptée à votre métier</span>`,
      intro: "Nous parlons le langage de votre secteur : nos solutions s'appuient sur des cas d'usage concrets et éprouvés.",
      items: [
        { icon: "🏥", title: "Santé & Cliniques", desc: "Prise de RDV automatisée, rappels patients, tri des appels, OCR ordonnances et dossiers." },
        { icon: "🏪", title: "E-commerce & Retail", desc: "Recommandations produits, support 24/7, suivi de commande WhatsApp, gestion stocks IA." },
        { icon: "🏢", title: "Immobilier", desc: "Qualification de prospects, visites virtuelles guidées par IA, génération d'annonces." },
        { icon: "⚖", title: "Juridique & Cabinets", desc: "Recherche dans dossiers, génération de clauses, classification automatique de documents." },
        { icon: "🏨", title: "Hôtellerie & Restauration", desc: "Réservations multilingues, conciergerie IA, gestion d'avis, menu interactif WhatsApp." },
        { icon: "🏭", title: "Industrie & Logistique", desc: "Maintenance prédictive, supervision IA, automatisation de la chaîne documentaire." },
      ],
    },
    process: {
      tag: "Notre méthode",
      titleHtml: `Un processus <span class="text-grad">clair et éprouvé</span>`,
      intro: "De la première discussion à la mise en production, chaque étape est cadrée pour garantir la valeur livrée.",
      steps: [
        { title: "Audit & cadrage", desc: "Compréhension de vos enjeux, identification des cas d'usage à fort ROI." },
        { title: "Prototype rapide", desc: "POC livré sous 2 à 3 semaines, validation concrète avant tout engagement." },
        { title: "Déploiement", desc: "Mise en production sur votre infrastructure, formation de vos équipes." },
        { title: "Suivi & évolution", desc: "Monitoring, optimisations continues et nouveaux cas d'usage à mesure." },
      ],
    },
    tech: {
      tag: "Stack technique",
      titleHtml: `Open-source d'abord, <span class="text-grad">souverain par défaut</span>`,
      intro: "Nous privilégions les technologies que vous pouvez auditer, contrôler et faire évoluer librement.",
    },
    testimonials: {
      tag: "Témoignages",
      titleHtml: `Ils nous ont fait <span class="text-grad">confiance</span>`,
      items: [
        { text: "NAXA a automatisé 80% de notre support WhatsApp. Notre équipe se concentre enfin sur les vraies demandes clients — et notre temps de réponse moyen est passé de 3h à 2 minutes.", initials: "SK", name: "Sara K.", role: "Directrice e-commerce", company: "Casablanca" },
        { text: "L'assistant IA local installé sur nos serveurs a transformé notre gestion documentaire. Et nos données restent chez nous — un argument décisif pour notre cabinet.", initials: "MR", name: "Mehdi R.", role: "Avocat associé", company: "Rabat" },
        { text: "Le chatbot multilingue gère nos réservations 24/7 en darija, français et anglais. Taux de conversion +35% sur les demandes WhatsApp depuis le déploiement.", initials: "LB", name: "Lina B.", role: "Manager hôtelière", company: "Marrakech" },
      ],
    },
    faq: {
      tag: "FAQ",
      titleHtml: `Vos <span class="text-grad">questions</span>, nos réponses`,
      items: [
        { q: "Qu'est-ce que l'IA locale, concrètement ?", a: "C'est une intelligence artificielle (modèle de langage, vision, OCR…) installée directement sur vos serveurs ou dans votre cloud privé. Aucune donnée ne transite par OpenAI, Google ou autre — vous gardez la souveraineté complète, ce qui est crucial pour la santé, le juridique, la finance et les administrations." },
        { q: "Combien coûte un projet NAXA ?", a: "Tout dépend de la complexité. Un chatbot WhatsApp démarre autour de 8 000 MAD, un assistant IA local complet entre 25 000 et 80 000 MAD. Nous proposons toujours un audit gratuit et un POC à coût maîtrisé avant tout engagement long." },
        { q: "En combien de temps ai-je un résultat ?", a: "Un prototype fonctionnel est livré en 2 à 3 semaines. Une mise en production complète prend généralement 6 à 10 semaines selon le périmètre." },
        { q: "Travaillez-vous avec mes outils existants (CRM, ERP, WhatsApp) ?", a: "Oui. Nous nous intégrons à HubSpot, Salesforce, Odoo, Sage, Pipedrive, Google Workspace, Microsoft 365, WhatsApp Business API, et tout outil disposant d'une API. Si l'API n'existe pas, nous construisons des connecteurs sur-mesure." },
        { q: "Et après le déploiement ?", a: "Nous proposons des forfaits de support et d'évolution mensuels. Vos équipes sont formées, et chaque solution est documentée pour rester maintenable même sans nous." },
      ],
    },
    cta: { title: "Prêt à automatiser votre activité ?", text: "Discutons de votre projet en 30 minutes — audit offert, sans engagement.", btn: "Réserver mon audit gratuit ›" },
    orgDescription: "Agence digitale marocaine spécialisée en Intelligence Artificielle locale, automatisation métier et chatbots WhatsApp.",
  },
  services: {
    hero: { tag: "Nos services", titleHtml: `Des services pensés pour <span class="text-grad">accélérer votre entreprise</span>`, sub: "Quatre offres, conçues pour s'imbriquer ou s'utiliser séparément, et toujours adaptées à votre maturité technique." },
    intro: { tag: "Nos prestations", titleHtml: `Quatre offres, <span class="text-grad">une intégration sur-mesure</span>`, text: "Du POC ponctuel à la transformation complète, choisissez le périmètre qui vous correspond." },
    cards: [
      { icon: "⚡", title: "IA locale (on-premise)", desc: "Nous installons, configurons et maintenons des modèles d'IA directement sur votre infrastructure : Llama, Mistral, Qwen, modèles de vision et d'OCR. Vos données ne quittent jamais vos serveurs.", list: ["Assistants documentaires RAG", "Recherche sémantique privée", "OCR factures, contrats, ordonnances", "Vision IA (contrôle qualité, comptage)", "Fine-tuning sur vos données"] },
      { icon: "⚙", title: "Automatisation métier", desc: "Nous connectons vos outils et orchestrons des workflows qui fonctionnent 24/7, sans intervention humaine. Vos équipes se concentrent sur ce qui crée de la valeur.", list: ["n8n & Make auto-hébergés", "Synchronisation CRM / ERP / mails", "Génération automatique de devis", "Reporting & alertes intelligentes", "RPA (saisie, extraction, scraping)"] },
      { icon: "💬", title: "Chatbots & assistants conversationnels", desc: "Des chatbots qui comprennent réellement vos clients, en français, arabe et darija — connectés à vos systèmes et capables d'agir, pas seulement de répondre.", list: ["WhatsApp Business API officielle", "Chatbots web & widgets", "Qualification & relance de leads", "Prise de RDV & paiement intégré", "Support client multicanal"] },
      { icon: "🎨", title: "Création digitale", desc: "Sites web, identités visuelles et campagnes pensés pour convertir. Conçus avec les dernières pratiques UX, optimisés SEO et préparés pour l'IA dès le départ.", list: ["Sites vitrine & landing pages", "E-commerce performant", "Branding & UI/UX", "SEO technique & contenu IA", "Maintenance & hébergement"] },
    ],
    pricing: {
      tag: "Formules", titleHtml: `Des engagements <span class="text-grad">à votre rythme</span>`, intro: "Du POC ponctuel au partenariat long-terme — nous adaptons la formule à votre maturité.",
      tiers: [
        { name: "Essentiel", price: "à partir de 8 000 MAD", desc: "Un cas d'usage ciblé livré clé en main : chatbot WhatsApp, automatisation simple, ou mini-site IA.", list: ["1 cas d'usage", "Livraison sous 3 semaines", "Formation incluse", "30 jours de support"] },
        { featured: true, badge: "Le plus demandé", name: "Croissance", price: "à partir de 25 000 MAD", desc: "Une suite complète automatisation + chatbot + IA légère, déployée et intégrée à vos outils.", list: ["3 à 5 cas d'usage", "Intégrations CRM / ERP", "Tableau de bord ROI", "3 mois de support"] },
        { name: "Souverain", price: "sur devis", desc: "IA locale complète sur votre infrastructure, fine-tuning, sécurité avancée, accompagnement long-terme.", list: ["Modèles déployés on-premise", "Fine-tuning sectoriel", "Conformité RGPD / ISO", "Suivi mensuel dédié"] },
      ],
    },
    cta: { title: "Une idée en tête ? Parlons-en.", text: "Audit gratuit de 30 minutes pour cadrer votre projet et identifier les automatisations à fort ROI.", btn: "Démarrer maintenant ›" },
  },
  solutions: {
    hero: { tag: "Solutions IA", titleHtml: `Des cas d'usage <span class="text-grad">concrets et déployés</span>`, sub: "Parce qu'une bonne solution IA résout un problème précis. Voici les usages les plus demandés par nos clients — chacun déployable en quelques semaines." },
    intro: { tag: "Cas d'usage IA", titleHtml: `Huit solutions <span class="text-grad">prêtes à déployer</span>`, text: "Chaque carte ci-dessous correspond à un cas d'usage éprouvé. Cliquez pour personnaliser votre demande selon vos besoins exacts." },
    cardCta: "Demander un devis ›",
    cards: [
      { icon: "📚", title: "Assistant documentaire (RAG)", desc: "Vos collaborateurs interrogent en langage naturel l'ensemble de vos documents internes : procédures, contrats, normes, archives. Réponses sourcées, en quelques secondes.", list: ["Indexation Word, PDF, Excel, mails", "Réponses avec citations", "Permissions par utilisateur", "Déploiement local ou cloud privé"] },
      { icon: "🧾", title: "OCR & extraction documentaire", desc: "Extraction automatique des données depuis factures, bons de commande, contrats, ordonnances — directement injectées dans votre ERP ou comptabilité.", list: ["Précision +95% sur factures FR/AR", "Validation humaine si doute", "Intégration Sage, Odoo, Excel", "Archivage automatique"] },
      { icon: "📱", title: "Chatbot WhatsApp commercial", desc: "Un agent IA disponible 24/7 sur WhatsApp pour qualifier vos prospects, répondre aux questions courantes et transférer aux humains quand il faut.", list: ["Multilingue (FR / AR / darija / EN)", "Catalogue produit & paiement", "Synchro CRM en temps réel", "Statistiques de conversion"] },
      { icon: "📊", title: "Reporting automatisé", desc: "Tableaux de bord qui s'auto-construisent à partir de vos données. Plus de copier-coller Excel : les rapports arrivent directement par mail ou Slack.", list: ["Connexion Google Sheets, SQL, API", "Alertes intelligentes", "Synthèses IA automatiques", "Envoi planifié"] },
      { icon: "📞", title: "Voice IA & téléphonie", desc: "Standard téléphonique IA, transcription d'appels, résumés automatiques. Vos commerciaux ne perdent plus une information.", list: ["Standard intelligent (IVR IA)", "Transcription FR / AR", "Résumé d'appel auto", "Détection de sentiment"] },
      { icon: "👁", title: "Vision industrielle", desc: "Contrôle qualité, comptage, lecture de plaques, détection d'anomalies. L'IA analyse vos flux vidéo en temps réel, sans cloud.", list: ["Caméras IP existantes réutilisées", "Inférence locale temps réel", "Alertes & rapports", "RGPD by design"] },
      { icon: "📅", title: "Prise de RDV intelligente", desc: "Vos clients réservent eux-mêmes par WhatsApp ou web, l'IA gère les conflits de planning, envoie les rappels et collecte les paiements.", list: ["Synchro Google / Outlook", "Rappels SMS / WhatsApp", "Annulations & report", "Paiement en ligne intégré"] },
      { icon: "🔍", title: "Veille & génération de contenu", desc: "Surveillance concurrentielle automatisée, génération de posts, fiches produit, descriptions SEO — adaptées à votre ton de marque.", list: ["Scraping & monitoring", "Génération multi-format", "Adaptation tone of voice", "Validation avant publication"] },
    ],
    realcases: {
      tag: "Cas réels", titleHtml: `Des solutions qui <span class="text-grad">tournent en production</span>`, intro: "Quelques retours de clients qui utilisent ces solutions au quotidien.",
      items: [
        { text: "L'OCR factures NAXA traite 1 200 factures par mois sans intervention. Notre comptable a récupéré 3 jours par mois — on a redéployé son temps sur l'analyse financière.", initials: "YA", name: "Yassine A.", role: "Directeur administratif", company: "Casablanca" },
        { text: "Notre assistant RAG documentaire répond en 3 secondes à des questions qui demandaient 30 minutes de recherche. Les juristes du cabinet l'utilisent tous les jours.", initials: "FB", name: "Fatima B.", role: "Cabinet juridique", company: "Rabat" },
        { text: "La voice IA gère 70% des appels entrants, qualifie les patients et prend les RDV. Notre standard téléphonique est devenu invisible — et nos patients sont satisfaits.", initials: "HM", name: "Dr. Hicham M.", role: "Centre médical", company: "Tanger" },
      ],
    },
    faq: {
      tag: "FAQ Solutions", titleHtml: `Tout ce qu'il faut <span class="text-grad">savoir</span> avant de démarrer`,
      items: [
        { q: "Combien de temps pour un premier prototype ?", a: "Entre 2 et 3 semaines pour un POC fonctionnel sur vos vraies données. Cela vous permet de valider concrètement la valeur avant tout engagement long. Une mise en production complète prend ensuite 4 à 8 semaines selon la complexité." },
        { q: "Vos solutions sont-elles compatibles avec mes outils existants ?", a: "Oui. Nous intégrons nativement HubSpot, Salesforce, Odoo, Sage, Pipedrive, Google Workspace, Microsoft 365, WhatsApp Business, et tout outil exposant une API. Pour les outils sans API, nous développons des connecteurs sur-mesure." },
        { q: "Mes données restent-elles vraiment chez moi ?", a: "Oui — c'est notre signature. Les modèles d'IA tournent sur vos serveurs ou dans votre cloud privé. Aucune donnée ne transite par OpenAI, Google ou autre service externe. C'est ce qui rend nos solutions adaptées aux secteurs réglementés : santé, juridique, finance, public." },
        { q: "Quelle autonomie ai-je après livraison ?", a: "Complète si vous le souhaitez. Vos équipes sont formées, chaque solution est documentée, et le code reste à vous. Vous pouvez faire évoluer la solution en interne, avec un freelance, ou continuer avec nous via un forfait mensuel de support et d'évolutions." },
        { q: "Peut-on ajouter d'autres cas d'usage plus tard ?", a: "Absolument. Une fois l'infrastructure IA en place (modèles, base vectorielle, automatisations), ajouter un nouveau cas d'usage prend généralement 1 à 2 semaines, à coût marginal. C'est l'effet de levier qu'offre une plateforme bien conçue dès le départ." },
        { q: "Quel budget prévoir pour une solution complète ?", a: "Un cas d'usage simple démarre autour de 8 000 MAD. Une solution intégrée avec infrastructure IA locale (modèles, vector DB, automatisations) se situe généralement entre 25 000 et 80 000 MAD, selon la complexité. Nous proposons toujours un audit gratuit et un POC à coût maîtrisé avant tout engagement long." },
      ],
    },
    cta: { title: "Votre cas d'usage n'est pas listé ?", text: "Nous concevons aussi des solutions IA sur-mesure. Décrivez-nous votre besoin — nous revenons avec une approche en 48h.", btn: "Discuter de mon projet ›" },
    breadcrumbName: "Solutions IA",
  },
  about: {
    hero: { tag: "À propos", titleHtml: `Une agence pensée pour <span class="text-grad">les entreprises ambitieuses</span>`, sub: "NAXA est née d'une conviction simple : l'IA ne doit pas être un produit qu'on consomme, mais un outil qu'on maîtrise. Nous aidons les entreprises marocaines à reprendre le contrôle de leur transformation numérique." },
    mission: {
      tag: "Notre mission", titleHtml: `Démocratiser l'IA <span class="text-grad">souveraine</span>`,
      paras: ["Trop d'entreprises envoient leurs données les plus sensibles à des modèles cloud étrangers, sans visibilité sur ce qu'il en advient. Nous pensons qu'il est possible — et nécessaire — de bâtir des solutions IA puissantes tout en gardant ses données chez soi.", "Notre métier : transformer cette conviction en réalité opérationnelle pour vous."],
      distinguishTitle: "Ce qui nous distingue",
      distinguishList: ["Approche IA locale par défaut", "Open-source plutôt que SaaS verrouillé", "POC rapides, ROI démontré", "Documentation et formation des équipes", "Support local, en français"],
    },
    values: {
      tag: "Nos valeurs", titleHtml: `Quatre principes <span class="text-grad">non négociables</span>`,
      items: [
        { icon: "🛡", title: "Souveraineté", desc: "Vos données sont votre actif le plus précieux. Elles restent chez vous, point." },
        { icon: "🎯", title: "ROI mesurable", desc: "Chaque projet est cadré avec des KPIs clairs. Pas de promesse vague, des résultats." },
        { icon: "🤝", title: "Transparence", desc: "Code documenté, choix techniques explicités, prix annoncés à l'avance." },
        { icon: "🚀", title: "Pragmatisme", desc: "On commence petit, on prouve la valeur, puis on étend. Pas de big bang." },
      ],
    },
    stats: [
      { num: 40, suffix: "+", label: "Projets livrés" },
      { num: 15, suffix: "+", label: "Secteurs couverts" },
      { num: 98, suffix: "%", label: "Clients satisfaits" },
      { num: 3, suffix: "x", label: "ROI moyen constaté" },
    ],
    team: {
      tag: "Équipe", titleHtml: `Une équipe <span class="text-grad">multi-disciplinaire</span>`, intro: "Ingénieurs IA, développeurs full-stack, designers UX et consultants métier — réunis sous un même toit pour livrer vite et bien.",
      members: [
        { initials: "KE", name: "Karim El M.", role: "Fondateur · IA & Stratégie" },
        { initials: "CH", name: "Chaymae H.", role: "Lead Design & UX" },
        { initials: "YA", name: "Younes A.", role: "Ingénieur ML" },
        { initials: "SO", name: "Salma O.", role: "Automatisation & Chatbots" },
      ],
    },
    cta: { title: "Travaillons ensemble", text: "Que vous ayez un projet précis ou une simple curiosité, nous prenons le temps d'en discuter sérieusement.", btn: "Prendre contact ›" },
  },
  contact: {
    hero: { tag: "Contact", titleHtml: `Parlons de <span class="text-grad">votre projet</span>`, sub: "Décrivez-nous votre besoin en quelques lignes — nous revenons vers vous sous 24h avec une première analyse gratuite." },
    info: {
      title: "Joignez-nous directement", text: "Nous répondons en quelques heures, du lundi au samedi.",
      phoneLabel: "Téléphone", whatsappLabel: "WhatsApp", whatsappLink: "Discuter en direct",
      emailLabel: "Email", locationLabel: "Localisation", locationValue: "Maroc — interventions à distance & sur site",
      hoursLabel: "Horaires", hoursValue: "Lun–Sam · 9h00 — 19h00",
    },
    form: {
      title: "Démarrer un projet", sub: "Réponse garantie sous 24h ouvrées.",
      nom: "Nom complet *", nomPh: "Votre nom",
      email: "Email *", emailPh: "vous@entreprise.ma",
      entreprise: "Entreprise", entreprisePh: "Nom de votre société",
      telephone: "Téléphone", telephonePh: "06 XX XX XX XX",
      service: "Quel service vous intéresse ? *", serviceDefault: "— Choisissez —",
      serviceOptions: ["IA locale (on-premise)", "Automatisation métier", "Chatbot WhatsApp / Web", "Création digitale (site, branding)", "Audit & conseil", "Autre / Pas encore sûr"],
      message: "Décrivez votre besoin *", messagePh: "Quelques lignes sur votre activité, votre besoin, votre échéance idéale...",
      submit: "Envoyer ma demande ›", note: "En envoyant ce formulaire, vous serez redirigé vers WhatsApp pour finaliser le contact.",
    },
  },
  merci: { tag: "Demande reçue", titleHtml: `Merci pour <span class="text-grad">votre message</span>`, sub: "Notre équipe revient vers vous sous 24h ouvrées. Pour une discussion immédiate, contactez-nous sur WhatsApp.", btnWa: "💬 Continuer sur WhatsApp", btnHome: "Retour à l'accueil" },
  nf: { tag: "Erreur 404", titleHtml: `Page <span class="text-grad">introuvable</span>`, sub: "La page que vous cherchez n'existe pas ou a été déplacée.", btnHome: "Retour à l'accueil", btnContact: "Nous contacter" },
};

const en = {
  techBadges,
  ui: {
    skip: "Skip to main content",
    logoAlt: "NAXA",
    menu: "Menu",
    langGroup: "Langue / Language / اللغة",
    whatsappFab: "Contact us on WhatsApp",
    verified: "Verified",
    verifiedTitle: "Verified client",
    ratingLabel: "Rating: 5 out of 5",
  },
  nav: {
    home: "Home", services: "Services", solutions: "AI Solutions",
    about: "About", contact: "Contact", cta: "Start a project",
  },
  footer: {
    brand: "Digital agency specialized in local AI, business automation and intelligent chatbots. Based in Morocco, serving ambitious companies.",
    colServices: "Services", colCompany: "Company", colContact: "Contact",
    servicesLinks: ["Local AI", "Automation", "Chatbots", "Digital creation"],
    location: "Morocco",
    copy: "© 2026 NAXA — All rights reserved.",
    tagline: "Local AI · Data sovereignty",
  },
  meta: {
    home: { title: "NAXA — Local AI, automation & chatbots for businesses", desc: "AI agency Morocco — NAXA deploys local Artificial Intelligence, business automation and WhatsApp chatbots for companies in Casablanca, Rabat, Marrakech and Tangier. Data sovereignty, measurable ROI." },
    services: { title: "Services — NAXA · Local AI, automation, chatbots", desc: "Discover NAXA services: local artificial intelligence, workflow automation, WhatsApp and web chatbots, digital creation." },
    solutions: { title: "AI Solutions — NAXA · Business use cases", desc: "NAXA AI solutions by use case: document assistant, invoice OCR, WhatsApp chatbot, accounting automation, industrial vision." },
    about: { title: "About — NAXA · The local AI & automation agency", desc: "NAXA, a Moroccan digital agency specialized in local AI and automation. Our vision, our values, our team." },
    contact: { title: "Contact — NAXA · Let's start your AI project", desc: "Contact NAXA to discuss your local AI, automation or chatbot project. Free audit, reply within 24h." },
    merci: { title: "Thank you — NAXA", desc: "Your request has been received. Our team will get back to you within 24h." },
    nf: { title: "Page not found (404) — NAXA", desc: "The requested page cannot be found. Return to the NAXA home page or contact us." },
  },
  home: {
    hero: {
      tag: "Local AI · Automation · Chatbots",
      titleHtml: `Your processes, <span class="text-grad">powered by AI</span><br>without ever losing your data.`,
      subHtml: `NAXA designs and deploys <strong>local Artificial Intelligence</strong>, business automation and chatbot solutions that fit your activity — full sovereignty, measurable ROI, and human support at every step.`,
      ctaAudit: "Free audit ›",
      ctaSolutions: "Discover our solutions",
      trust: ["100% on-premise data", "Open-source models", "GDPR / Law 09-08 compliant"],
    },
    stats: [
      { num: 40, suffix: "+", label: "Projects deployed" },
      { num: 70, suffix: "%", label: "Repetitive tasks automated" },
      { num: 24, suffix: "/7", label: "Chatbot availability" },
      { num: 100, suffix: "%", label: "Sovereign data" },
    ],
    services: {
      tag: "Our expertise",
      titleHtml: `Three pillars, one mission: <span class="text-grad">free your productivity</span>`,
      intro: "From AI deployed on your servers to workflow automation and intelligent chatbots — everything natively integrated with your tools.",
      cards: [
        { icon: "⚡", title: "Local Artificial Intelligence", desc: "Deployment of open-source LLM models (Llama, Mistral, Qwen) directly on your infrastructure. Your data never leaves your servers.", list: ["RAG over internal documents", "Tailored business assistants", "AI vision & advanced OCR", "Sector-specific fine-tuning"] },
        { icon: "⚙", title: "Business automation", desc: "Connect your tools (CRM, ERP, email, accounting) and let the workflows run on their own. Immediate time savings, human errors eliminated.", list: ["Self-hosted n8n, Make, Zapier", "Custom API integrations", "Automated reporting & dashboards", "HR, finance, logistics processes"] },
        { icon: "💬", title: "Intelligent chatbots", desc: "WhatsApp, web and Messenger chatbots powered by AI, able to understand, qualify and convert 24/7, in French, Arabic and Darija.", list: ["WhatsApp Business API", "Multilingual customer support", "Lead qualification", "CRM & payment integration"] },
      ],
    },
    sectors: {
      tag: "Industries",
      titleHtml: `Expertise <span class="text-grad">tailored to your business</span>`,
      intro: "We speak the language of your industry: our solutions are built on concrete, proven use cases.",
      items: [
        { icon: "🏥", title: "Healthcare & Clinics", desc: "Automated appointment booking, patient reminders, call triage, OCR of prescriptions and records." },
        { icon: "🏪", title: "E-commerce & Retail", desc: "Product recommendations, 24/7 support, WhatsApp order tracking, AI inventory management." },
        { icon: "🏢", title: "Real estate", desc: "Lead qualification, AI-guided virtual tours, listing generation." },
        { icon: "⚖", title: "Legal & Law firms", desc: "Search across case files, clause generation, automatic document classification." },
        { icon: "🏨", title: "Hospitality & Restaurants", desc: "Multilingual bookings, AI concierge, review management, interactive WhatsApp menu." },
        { icon: "🏭", title: "Industry & Logistics", desc: "Predictive maintenance, AI monitoring, automation of the document chain." },
      ],
    },
    process: {
      tag: "Our method",
      titleHtml: `A clear and <span class="text-grad">proven process</span>`,
      intro: "From the first discussion to production, every step is framed to guarantee delivered value.",
      steps: [
        { title: "Audit & scoping", desc: "Understanding your challenges, identifying high-ROI use cases." },
        { title: "Rapid prototype", desc: "POC delivered within 2 to 3 weeks, concrete validation before any commitment." },
        { title: "Deployment", desc: "Production rollout on your infrastructure, training of your teams." },
        { title: "Support & evolution", desc: "Monitoring, continuous optimization and new use cases over time." },
      ],
    },
    tech: {
      tag: "Tech stack",
      titleHtml: `Open-source first, <span class="text-grad">sovereign by default</span>`,
      intro: "We favor technologies you can audit, control and evolve freely.",
    },
    testimonials: {
      tag: "Testimonials",
      titleHtml: `They placed their <span class="text-grad">trust in us</span>`,
      items: [
        { text: "NAXA automated 80% of our WhatsApp support. Our team can finally focus on real customer requests — and our average response time dropped from 3h to 2 minutes.", initials: "SK", name: "Sara K.", role: "E-commerce Director", company: "Casablanca" },
        { text: "The local AI assistant installed on our servers transformed our document management. And our data stays with us — a decisive argument for our firm.", initials: "MR", name: "Mehdi R.", role: "Partner lawyer", company: "Rabat" },
        { text: "The multilingual chatbot handles our bookings 24/7 in Darija, French and English. Conversion rate +35% on WhatsApp requests since deployment.", initials: "LB", name: "Lina B.", role: "Hotel manager", company: "Marrakech" },
      ],
    },
    faq: {
      tag: "FAQ",
      titleHtml: `Your <span class="text-grad">questions</span>, our answers`,
      items: [
        { q: "What is local AI, in concrete terms?", a: "It is an artificial intelligence (language model, vision, OCR…) installed directly on your servers or in your private cloud. No data passes through OpenAI, Google or others — you keep full sovereignty, which is crucial for healthcare, legal, finance and public administration." },
        { q: "How much does a NAXA project cost?", a: "It depends on complexity. A WhatsApp chatbot starts around 8,000 MAD, a complete local AI assistant between 25,000 and 80,000 MAD. We always offer a free audit and a cost-controlled POC before any long-term commitment." },
        { q: "How quickly do I get a result?", a: "A working prototype is delivered in 2 to 3 weeks. A full production rollout generally takes 6 to 10 weeks depending on scope." },
        { q: "Do you work with my existing tools (CRM, ERP, WhatsApp)?", a: "Yes. We integrate with HubSpot, Salesforce, Odoo, Sage, Pipedrive, Google Workspace, Microsoft 365, WhatsApp Business API, and any tool with an API. If the API doesn't exist, we build custom connectors." },
        { q: "And after deployment?", a: "We offer monthly support and evolution plans. Your teams are trained, and every solution is documented to stay maintainable even without us." },
      ],
    },
    cta: { title: "Ready to automate your business?", text: "Let's discuss your project in 30 minutes — free audit, no commitment.", btn: "Book my free audit ›" },
    orgDescription: "Moroccan digital agency specialized in local Artificial Intelligence, business automation and WhatsApp chatbots.",
  },
  services: {
    hero: { tag: "Our services", titleHtml: `Services designed to <span class="text-grad">accelerate your company</span>`, sub: "Four offers, designed to combine or be used separately, and always adapted to your technical maturity." },
    intro: { tag: "Our offerings", titleHtml: `Four offers, <span class="text-grad">one tailored integration</span>`, text: "From a one-off POC to full transformation, choose the scope that fits you." },
    cards: [
      { icon: "⚡", title: "Local AI (on-premise)", desc: "We install, configure and maintain AI models directly on your infrastructure: Llama, Mistral, Qwen, vision and OCR models. Your data never leaves your servers.", list: ["RAG document assistants", "Private semantic search", "OCR for invoices, contracts, prescriptions", "AI vision (quality control, counting)", "Fine-tuning on your data"] },
      { icon: "⚙", title: "Business automation", desc: "We connect your tools and orchestrate workflows that run 24/7, without human intervention. Your teams focus on what creates value.", list: ["Self-hosted n8n & Make", "CRM / ERP / email synchronization", "Automatic quote generation", "Smart reporting & alerts", "RPA (data entry, extraction, scraping)"] },
      { icon: "💬", title: "Chatbots & conversational assistants", desc: "Chatbots that truly understand your customers, in French, Arabic and Darija — connected to your systems and able to act, not just answer.", list: ["Official WhatsApp Business API", "Web chatbots & widgets", "Lead qualification & follow-up", "Booking & integrated payment", "Multichannel customer support"] },
      { icon: "🎨", title: "Digital creation", desc: "Websites, visual identities and campaigns designed to convert. Built with the latest UX practices, SEO-optimized and AI-ready from the start.", list: ["Showcase sites & landing pages", "High-performance e-commerce", "Branding & UI/UX", "Technical SEO & AI content", "Maintenance & hosting"] },
    ],
    pricing: {
      tag: "Plans", titleHtml: `Commitments <span class="text-grad">at your pace</span>`, intro: "From a one-off POC to a long-term partnership — we adapt the plan to your maturity.",
      tiers: [
        { name: "Essential", price: "from 8,000 MAD", desc: "A targeted use case delivered turnkey: WhatsApp chatbot, simple automation, or AI mini-site.", list: ["1 use case", "Delivery within 3 weeks", "Training included", "30 days of support"] },
        { featured: true, badge: "Most popular", name: "Growth", price: "from 25,000 MAD", desc: "A complete automation + chatbot + light AI suite, deployed and integrated with your tools.", list: ["3 to 5 use cases", "CRM / ERP integrations", "ROI dashboard", "3 months of support"] },
        { name: "Sovereign", price: "on quote", desc: "Complete local AI on your infrastructure, fine-tuning, advanced security, long-term support.", list: ["Models deployed on-premise", "Sector-specific fine-tuning", "GDPR / ISO compliance", "Dedicated monthly follow-up"] },
      ],
    },
    cta: { title: "Got an idea? Let's talk.", text: "Free 30-minute audit to frame your project and identify high-ROI automations.", btn: "Get started now ›" },
  },
  solutions: {
    hero: { tag: "AI Solutions", titleHtml: `Concrete, <span class="text-grad">deployed use cases</span>`, sub: "Because a good AI solution solves a specific problem. Here are the most requested use cases from our clients — each deployable in a few weeks." },
    intro: { tag: "AI use cases", titleHtml: `Eight solutions <span class="text-grad">ready to deploy</span>`, text: "Each card below corresponds to a proven use case. Click to customize your request to your exact needs." },
    cardCta: "Request a quote ›",
    cards: [
      { icon: "📚", title: "Document assistant (RAG)", desc: "Your staff query all your internal documents in natural language: procedures, contracts, standards, archives. Sourced answers in seconds.", list: ["Indexing Word, PDF, Excel, email", "Answers with citations", "Per-user permissions", "Local or private cloud deployment"] },
      { icon: "🧾", title: "OCR & document extraction", desc: "Automatic data extraction from invoices, purchase orders, contracts, prescriptions — injected directly into your ERP or accounting.", list: ["+95% accuracy on FR/AR invoices", "Human validation if in doubt", "Sage, Odoo, Excel integration", "Automatic archiving"] },
      { icon: "📱", title: "Commercial WhatsApp chatbot", desc: "An AI agent available 24/7 on WhatsApp to qualify your prospects, answer common questions and hand over to humans when needed.", list: ["Multilingual (FR / AR / Darija / EN)", "Product catalog & payment", "Real-time CRM sync", "Conversion statistics"] },
      { icon: "📊", title: "Automated reporting", desc: "Dashboards that build themselves from your data. No more Excel copy-paste: reports arrive directly by email or Slack.", list: ["Google Sheets, SQL, API connection", "Smart alerts", "Automatic AI summaries", "Scheduled delivery"] },
      { icon: "📞", title: "Voice AI & telephony", desc: "AI phone switchboard, call transcription, automatic summaries. Your sales reps never miss a piece of information.", list: ["Smart switchboard (AI IVR)", "FR / AR transcription", "Automatic call summary", "Sentiment detection"] },
      { icon: "👁", title: "Industrial vision", desc: "Quality control, counting, plate reading, anomaly detection. AI analyzes your video streams in real time, without cloud.", list: ["Existing IP cameras reused", "Real-time local inference", "Alerts & reports", "GDPR by design"] },
      { icon: "📅", title: "Smart appointment booking", desc: "Your clients book themselves via WhatsApp or web, AI manages scheduling conflicts, sends reminders and collects payments.", list: ["Google / Outlook sync", "SMS / WhatsApp reminders", "Cancellations & rescheduling", "Integrated online payment"] },
      { icon: "🔍", title: "Monitoring & content generation", desc: "Automated competitive monitoring, generation of posts, product sheets, SEO descriptions — tailored to your brand voice.", list: ["Scraping & monitoring", "Multi-format generation", "Tone-of-voice adaptation", "Validation before publishing"] },
    ],
    realcases: {
      tag: "Real cases", titleHtml: `Solutions that <span class="text-grad">run in production</span>`, intro: "A few words from clients who use these solutions every day.",
      items: [
        { text: "NAXA's invoice OCR processes 1,200 invoices a month with no intervention. Our accountant got back 3 days a month — we redeployed that time to financial analysis.", initials: "YA", name: "Yassine A.", role: "Administrative Director", company: "Casablanca" },
        { text: "Our RAG document assistant answers in 3 seconds questions that used to require 30 minutes of research. The firm's lawyers use it every day.", initials: "FB", name: "Fatima B.", role: "Law firm", company: "Rabat" },
        { text: "The voice AI handles 70% of incoming calls, qualifies patients and books appointments. Our switchboard became invisible — and our patients are happy.", initials: "HM", name: "Dr. Hicham M.", role: "Medical center", company: "Tangier" },
      ],
    },
    faq: {
      tag: "Solutions FAQ", titleHtml: `Everything you need to <span class="text-grad">know</span> before starting`,
      items: [
        { q: "How long for a first prototype?", a: "Between 2 and 3 weeks for a working POC on your real data. This lets you concretely validate the value before any long commitment. A full production rollout then takes 4 to 8 weeks depending on complexity." },
        { q: "Are your solutions compatible with my existing tools?", a: "Yes. We natively integrate HubSpot, Salesforce, Odoo, Sage, Pipedrive, Google Workspace, Microsoft 365, WhatsApp Business, and any tool that exposes an API. For tools without an API, we develop custom connectors." },
        { q: "Does my data really stay with me?", a: "Yes — it's our signature. The AI models run on your servers or in your private cloud. No data passes through OpenAI, Google or any external service. This is what makes our solutions suitable for regulated sectors: healthcare, legal, finance, public." },
        { q: "How much autonomy do I have after delivery?", a: "Full, if you wish. Your teams are trained, every solution is documented, and the code is yours. You can evolve the solution in-house, with a freelancer, or continue with us via a monthly support and evolution plan." },
        { q: "Can we add other use cases later?", a: "Absolutely. Once the AI infrastructure is in place (models, vector database, automations), adding a new use case generally takes 1 to 2 weeks, at marginal cost. That's the leverage a well-designed platform offers from the start." },
        { q: "What budget should I plan for a full solution?", a: "A simple use case starts around 8,000 MAD. An integrated solution with local AI infrastructure (models, vector DB, automations) generally sits between 25,000 and 80,000 MAD, depending on complexity. We always offer a free audit and a cost-controlled POC before any long commitment." },
      ],
    },
    cta: { title: "Your use case isn't listed?", text: "We also design custom AI solutions. Describe your need — we come back with an approach within 48h.", btn: "Discuss my project ›" },
    breadcrumbName: "AI Solutions",
  },
  about: {
    hero: { tag: "About", titleHtml: `An agency built for <span class="text-grad">ambitious companies</span>`, sub: "NAXA was born from a simple conviction: AI should not be a product you consume, but a tool you master. We help Moroccan companies regain control of their digital transformation." },
    mission: {
      tag: "Our mission", titleHtml: `Democratizing <span class="text-grad">sovereign AI</span>`,
      paras: ["Too many companies send their most sensitive data to foreign cloud models, with no visibility on what happens to it. We believe it is possible — and necessary — to build powerful AI solutions while keeping your data at home.", "Our job: turning this conviction into operational reality for you."],
      distinguishTitle: "What sets us apart",
      distinguishList: ["Local-AI approach by default", "Open-source rather than locked-in SaaS", "Fast POCs, proven ROI", "Documentation and team training", "Local support, in French"],
    },
    values: {
      tag: "Our values", titleHtml: `Four <span class="text-grad">non-negotiable principles</span>`,
      items: [
        { icon: "🛡", title: "Sovereignty", desc: "Your data is your most precious asset. It stays with you, full stop." },
        { icon: "🎯", title: "Measurable ROI", desc: "Every project is framed with clear KPIs. No vague promises, results." },
        { icon: "🤝", title: "Transparency", desc: "Documented code, explained technical choices, prices announced upfront." },
        { icon: "🚀", title: "Pragmatism", desc: "We start small, prove the value, then scale. No big bang." },
      ],
    },
    stats: [
      { num: 40, suffix: "+", label: "Projects delivered" },
      { num: 15, suffix: "+", label: "Sectors covered" },
      { num: 98, suffix: "%", label: "Satisfied clients" },
      { num: 3, suffix: "x", label: "Average observed ROI" },
    ],
    team: {
      tag: "Team", titleHtml: `A <span class="text-grad">multi-disciplinary team</span>`, intro: "AI engineers, full-stack developers, UX designers and business consultants — under one roof to deliver fast and well.",
      members: [
        { initials: "KE", name: "Karim El M.", role: "Founder · AI & Strategy" },
        { initials: "CH", name: "Chaymae H.", role: "Lead Design & UX" },
        { initials: "YA", name: "Younes A.", role: "ML Engineer" },
        { initials: "SO", name: "Salma O.", role: "Automation & Chatbots" },
      ],
    },
    cta: { title: "Let's work together", text: "Whether you have a precise project or just curiosity, we take the time to discuss it seriously.", btn: "Get in touch ›" },
  },
  contact: {
    hero: { tag: "Contact", titleHtml: `Let's talk about <span class="text-grad">your project</span>`, sub: "Describe your need in a few lines — we get back to you within 24h with a first free analysis." },
    info: {
      title: "Reach us directly", text: "We reply within a few hours, Monday to Saturday.",
      phoneLabel: "Phone", whatsappLabel: "WhatsApp", whatsappLink: "Chat live",
      emailLabel: "Email", locationLabel: "Location", locationValue: "Morocco — remote & on-site interventions",
      hoursLabel: "Hours", hoursValue: "Mon–Sat · 9:00 AM — 7:00 PM",
    },
    form: {
      title: "Start a project", sub: "Guaranteed reply within 24 business hours.",
      nom: "Full name *", nomPh: "Your name",
      email: "Email *", emailPh: "you@company.ma",
      entreprise: "Company", entreprisePh: "Your company name",
      telephone: "Phone", telephonePh: "06 XX XX XX XX",
      service: "Which service interests you? *", serviceDefault: "— Choose —",
      serviceOptions: ["Local AI (on-premise)", "Business automation", "WhatsApp / Web chatbot", "Digital creation (site, branding)", "Audit & consulting", "Other / Not sure yet"],
      message: "Describe your need *", messagePh: "A few lines about your activity, your need, your ideal timeline...",
      submit: "Send my request ›", note: "By submitting this form, you will be redirected to WhatsApp to finalize the contact.",
    },
  },
  merci: { tag: "Request received", titleHtml: `Thank you for <span class="text-grad">your message</span>`, sub: "Our team gets back to you within 24 business hours. For an immediate chat, reach us on WhatsApp.", btnWa: "💬 Continue on WhatsApp", btnHome: "Back to home" },
  nf: { tag: "Error 404", titleHtml: `Page <span class="text-grad">not found</span>`, sub: "The page you are looking for doesn't exist or has been moved.", btnHome: "Back to home", btnContact: "Contact us" },
};

const ar = {
  techBadges,
  ui: {
    skip: "انتقل إلى المحتوى الرئيسي",
    logoAlt: "NAXA",
    menu: "القائمة",
    langGroup: "Langue / Language / اللغة",
    whatsappFab: "تواصل معنا عبر واتساب",
    verified: "موثَّق",
    verifiedTitle: "عميل موثَّق",
    ratingLabel: "التقييم: 5 من 5",
  },
  nav: {
    home: "الرئيسية", services: "الخدمات", solutions: "حلول الذكاء الاصطناعي",
    about: "من نحن", contact: "اتصل بنا", cta: "ابدأ مشروعك",
  },
  footer: {
    brand: "وكالة رقمية متخصصة في الذكاء الاصطناعي المحلي، وأتمتة الأعمال، وروبوتات المحادثة الذكية. مقرها المغرب، في خدمة الشركات الطموحة.",
    colServices: "الخدمات", colCompany: "الشركة", colContact: "اتصل بنا",
    servicesLinks: ["الذكاء الاصطناعي المحلي", "الأتمتة", "روبوتات المحادثة", "الإبداع الرقمي"],
    location: "المغرب",
    copy: "© 2026 NAXA — جميع الحقوق محفوظة.",
    tagline: "ذكاء اصطناعي محلي · سيادة البيانات",
  },
  meta: {
    home: { title: "NAXA — ذكاء اصطناعي محلي، أتمتة وروبوتات محادثة للشركات", desc: "وكالة ذكاء اصطناعي بالمغرب — تنشر NAXA الذكاء الاصطناعي المحلي وأتمتة الأعمال وروبوتات واتساب للشركات في الدار البيضاء والرباط ومراكش وطنجة. سيادة البيانات وعائد استثمار قابل للقياس." },
    services: { title: "الخدمات — NAXA · ذكاء اصطناعي محلي، أتمتة، روبوتات محادثة", desc: "اكتشف خدمات NAXA: الذكاء الاصطناعي المحلي، أتمتة سير العمل، روبوتات واتساب والويب، والإبداع الرقمي." },
    solutions: { title: "حلول الذكاء الاصطناعي — NAXA · حالات استخدام للأعمال", desc: "حلول الذكاء الاصطناعي من NAXA حسب حالة الاستخدام: مساعد المستندات، استخراج الفواتير OCR، روبوت واتساب، أتمتة المحاسبة، الرؤية الصناعية." },
    about: { title: "من نحن — NAXA · وكالة الذكاء الاصطناعي المحلي والأتمتة", desc: "NAXA، وكالة رقمية مغربية متخصصة في الذكاء الاصطناعي المحلي والأتمتة. رؤيتنا، قيمنا، فريقنا." },
    contact: { title: "اتصل بنا — NAXA · لنبدأ مشروع الذكاء الاصطناعي الخاص بك", desc: "تواصل مع NAXA لمناقشة مشروعك في الذكاء الاصطناعي المحلي أو الأتمتة أو روبوتات المحادثة. تدقيق مجاني، رد خلال 24 ساعة." },
    merci: { title: "شكراً — NAXA", desc: "تم استلام طلبك. سيعاود فريقنا التواصل معك خلال 24 ساعة." },
    nf: { title: "الصفحة غير موجودة (404) — NAXA", desc: "الصفحة المطلوبة غير موجودة. عُد إلى الصفحة الرئيسية لـ NAXA أو تواصل معنا." },
  },
  home: {
    hero: {
      tag: "ذكاء اصطناعي محلي · أتمتة · روبوتات محادثة",
      titleHtml: `عملياتك، <span class="text-grad">معزَّزة بالذكاء الاصطناعي</span><br>دون أن تفقد بياناتك أبداً.`,
      subHtml: `تصمم NAXA وتنشر حلول <strong>الذكاء الاصطناعي المحلي</strong> وأتمتة الأعمال وروبوتات المحادثة التي تندمج مع نشاطك — سيادة كاملة، عائد استثمار قابل للقياس، ومرافقة بشرية في كل خطوة.`,
      ctaAudit: "تدقيق مجاني ›",
      ctaSolutions: "اكتشف حلولنا",
      trust: ["بيانات محلية 100٪", "نماذج مفتوحة المصدر", "متوافق مع GDPR / القانون 09-08"],
    },
    stats: [
      { num: 40, suffix: "+", label: "مشاريع منجزة" },
      { num: 70, suffix: "%", label: "مهام متكررة مؤتمتة" },
      { num: 24, suffix: "/7", label: "توفر روبوت المحادثة" },
      { num: 100, suffix: "%", label: "بيانات سيادية" },
    ],
    services: {
      tag: "خبراتنا",
      titleHtml: `ثلاث ركائز، ومهمة واحدة: <span class="text-grad">إطلاق إنتاجيتك</span>`,
      intro: "من الذكاء الاصطناعي المنشور على خوادمك إلى أتمتة سير عملك وصولاً إلى روبوتات المحادثة الذكية — كل ذلك مدمج بشكل أصيل مع أدواتك.",
      cards: [
        { icon: "⚡", title: "الذكاء الاصطناعي المحلي", desc: "نشر نماذج لغوية مفتوحة المصدر (Llama، Mistral، Qwen) مباشرة على بنيتك التحتية. بياناتك لا تغادر خوادمك أبداً.", list: ["RAG على المستندات الداخلية", "مساعدون مهنيون مخصصون", "رؤية بالذكاء الاصطناعي وOCR متقدم", "ضبط دقيق حسب القطاع"] },
        { icon: "⚙", title: "أتمتة الأعمال", desc: "اربط أدواتك (CRM، ERP، البريد، المحاسبة) ودع سير العمل يعمل وحده. توفير فوري للوقت، وإزالة الأخطاء البشرية.", list: ["n8n، Make، Zapier مستضافة ذاتياً", "تكاملات API مخصصة", "تقارير ولوحات تلقائية", "عمليات الموارد البشرية والمالية واللوجستيك"] },
        { icon: "💬", title: "روبوتات محادثة ذكية", desc: "روبوتات واتساب والويب وماسنجر معززة بالذكاء الاصطناعي، قادرة على الفهم والتأهيل والتحويل على مدار الساعة، بالفرنسية والعربية والدارجة.", list: ["WhatsApp Business API", "دعم عملاء متعدد اللغات", "تأهيل العملاء المحتملين", "ربط بالـ CRM والدفع"] },
      ],
    },
    sectors: {
      tag: "القطاعات",
      titleHtml: `خبرة <span class="text-grad">مكيَّفة مع مجالك</span>`,
      intro: "نتحدث لغة قطاعك: حلولنا مبنية على حالات استخدام ملموسة ومثبتة.",
      items: [
        { icon: "🏥", title: "الصحة والعيادات", desc: "حجز المواعيد آلياً، تذكير المرضى، فرز المكالمات، استخراج الوصفات والملفات OCR." },
        { icon: "🏪", title: "التجارة الإلكترونية والتجزئة", desc: "توصيات المنتجات، دعم على مدار الساعة، تتبع الطلبات عبر واتساب، إدارة المخزون بالذكاء الاصطناعي." },
        { icon: "🏢", title: "العقارات", desc: "تأهيل العملاء المحتملين، جولات افتراضية موجَّهة بالذكاء الاصطناعي، توليد الإعلانات." },
        { icon: "⚖", title: "القانون والمكاتب", desc: "البحث في الملفات، توليد البنود، تصنيف المستندات تلقائياً." },
        { icon: "🏨", title: "الضيافة والمطاعم", desc: "حجوزات متعددة اللغات، خدمة استقبال بالذكاء الاصطناعي، إدارة التقييمات، قائمة تفاعلية عبر واتساب." },
        { icon: "🏭", title: "الصناعة واللوجستيك", desc: "صيانة تنبؤية، إشراف بالذكاء الاصطناعي، أتمتة سلسلة المستندات." },
      ],
    },
    process: {
      tag: "منهجيتنا",
      titleHtml: `عملية <span class="text-grad">واضحة ومثبتة</span>`,
      intro: "من النقاش الأول إلى الإنتاج، كل خطوة مؤطَّرة لضمان القيمة المُسلَّمة.",
      steps: [
        { title: "التدقيق والتأطير", desc: "فهم تحدياتك، وتحديد حالات الاستخدام ذات العائد المرتفع." },
        { title: "نموذج أولي سريع", desc: "POC يُسلَّم خلال أسبوعين إلى ثلاثة، بتحقق ملموس قبل أي التزام." },
        { title: "النشر", desc: "الإطلاق في الإنتاج على بنيتك التحتية، وتدريب فرقك." },
        { title: "المتابعة والتطوير", desc: "مراقبة، وتحسينات مستمرة، وحالات استخدام جديدة مع الوقت." },
      ],
    },
    tech: {
      tag: "الحزمة التقنية",
      titleHtml: `المصدر المفتوح أولاً، <span class="text-grad">وسيادي افتراضياً</span>`,
      intro: "نفضّل التقنيات التي يمكنك تدقيقها والتحكم بها وتطويرها بحرية.",
    },
    testimonials: {
      tag: "شهادات",
      titleHtml: `لقد منحونا <span class="text-grad">ثقتهم</span>`,
      items: [
        { text: "أتمتت NAXA 80٪ من دعم واتساب لدينا. أصبح فريقنا يركّز أخيراً على طلبات العملاء الحقيقية — وانخفض متوسط زمن الرد من 3 ساعات إلى دقيقتين.", initials: "SK", name: "Sara K.", role: "مديرة التجارة الإلكترونية", company: "الدار البيضاء" },
        { text: "حوّل مساعد الذكاء الاصطناعي المحلي المثبَّت على خوادمنا إدارة مستنداتنا. وبياناتنا تبقى لدينا — حجة حاسمة لمكتبنا.", initials: "MR", name: "Mehdi R.", role: "محامٍ شريك", company: "الرباط" },
        { text: "يدير روبوت المحادثة متعدد اللغات حجوزاتنا على مدار الساعة بالدارجة والفرنسية والإنجليزية. ارتفع معدل التحويل بنسبة 35٪ على طلبات واتساب منذ الإطلاق.", initials: "LB", name: "Lina B.", role: "مديرة فندق", company: "مراكش" },
      ],
    },
    faq: {
      tag: "الأسئلة الشائعة",
      titleHtml: `<span class="text-grad">أسئلتكم</span>، وأجوبتنا`,
      items: [
        { q: "ما هو الذكاء الاصطناعي المحلي عملياً؟", a: "هو ذكاء اصطناعي (نموذج لغوي، رؤية، OCR…) مثبَّت مباشرة على خوادمك أو في سحابتك الخاصة. لا تمر أي بيانات عبر OpenAI أو Google أو غيرهما — تحتفظ بالسيادة الكاملة، وهو أمر حاسم للصحة والقانون والمالية والإدارات." },
        { q: "كم تكلفة مشروع NAXA؟", a: "يعتمد على التعقيد. يبدأ روبوت واتساب حول 8 000 درهم، ومساعد ذكاء اصطناعي محلي كامل بين 25 000 و80 000 درهم. نقدّم دائماً تدقيقاً مجانياً وPOC بتكلفة محكومة قبل أي التزام طويل." },
        { q: "في كم من الوقت أحصل على نتيجة؟", a: "يُسلَّم نموذج أولي عملي خلال أسبوعين إلى ثلاثة. ويستغرق الإطلاق الكامل في الإنتاج عادة من 6 إلى 10 أسابيع حسب النطاق." },
        { q: "هل تعملون مع أدواتي الحالية (CRM، ERP، واتساب)؟", a: "نعم. نتكامل مع HubSpot وSalesforce وOdoo وSage وPipedrive وGoogle Workspace وMicrosoft 365 وWhatsApp Business API وأي أداة لديها API. وإن لم يوجد API، نبني موصِّلات مخصصة." },
        { q: "وماذا بعد النشر؟", a: "نقدّم باقات شهرية للدعم والتطوير. يتم تدريب فرقك، وكل حل موثَّق ليبقى قابلاً للصيانة حتى بدوننا." },
      ],
    },
    cta: { title: "هل أنت مستعد لأتمتة نشاطك؟", text: "لنناقش مشروعك في 30 دقيقة — تدقيق مجاني، دون التزام.", btn: "احجز تدقيقي المجاني ›" },
    orgDescription: "وكالة رقمية مغربية متخصصة في الذكاء الاصطناعي المحلي وأتمتة الأعمال وروبوتات واتساب.",
  },
  services: {
    hero: { tag: "خدماتنا", titleHtml: `خدمات مصمَّمة <span class="text-grad">لتسريع شركتك</span>`, sub: "أربعة عروض، مصمَّمة لتتكامل أو تُستخدم منفصلة، ودائماً مكيَّفة مع نضجك التقني." },
    intro: { tag: "عروضنا", titleHtml: `أربعة عروض، <span class="text-grad">وتكامل مخصص</span>`, text: "من POC ظرفي إلى تحول كامل، اختر النطاق الذي يناسبك." },
    cards: [
      { icon: "⚡", title: "ذكاء اصطناعي محلي (on-premise)", desc: "نثبّت ونضبط ونصون نماذج الذكاء الاصطناعي مباشرة على بنيتك التحتية: Llama، Mistral، Qwen، نماذج الرؤية وOCR. بياناتك لا تغادر خوادمك أبداً.", list: ["مساعدو مستندات RAG", "بحث دلالي خاص", "OCR للفواتير والعقود والوصفات", "رؤية بالذكاء الاصطناعي (مراقبة الجودة، العد)", "ضبط دقيق على بياناتك"] },
      { icon: "⚙", title: "أتمتة الأعمال", desc: "نربط أدواتك وننسّق سير عمل يعمل على مدار الساعة دون تدخل بشري. تركّز فرقك على ما يصنع القيمة.", list: ["n8n وMake مستضافة ذاتياً", "مزامنة CRM / ERP / البريد", "توليد عروض الأسعار آلياً", "تقارير وتنبيهات ذكية", "RPA (إدخال، استخراج، scraping)"] },
      { icon: "💬", title: "روبوتات محادثة ومساعدون محادثيون", desc: "روبوتات تفهم عملاءك حقاً، بالفرنسية والعربية والدارجة — مرتبطة بأنظمتك وقادرة على التصرف، لا الرد فقط.", list: ["WhatsApp Business API الرسمية", "روبوتات ويب وأدوات", "تأهيل ومتابعة العملاء المحتملين", "حجز المواعيد والدفع المدمج", "دعم عملاء متعدد القنوات"] },
      { icon: "🎨", title: "الإبداع الرقمي", desc: "مواقع وهويات بصرية وحملات مصمَّمة للتحويل. مبنية بأحدث ممارسات تجربة المستخدم، ومحسَّنة لمحركات البحث، وجاهزة للذكاء الاصطناعي منذ البداية.", list: ["مواقع تعريفية وصفحات هبوط", "تجارة إلكترونية عالية الأداء", "هوية وتصميم واجهات", "SEO تقني ومحتوى بالذكاء الاصطناعي", "صيانة واستضافة"] },
    ],
    pricing: {
      tag: "الباقات", titleHtml: `التزامات <span class="text-grad">على إيقاعك</span>`, intro: "من POC ظرفي إلى شراكة طويلة الأمد — نكيّف الباقة مع نضجك.",
      tiers: [
        { name: "الأساسية", price: "ابتداءً من 8 000 درهم", desc: "حالة استخدام مستهدفة تُسلَّم جاهزة: روبوت واتساب، أتمتة بسيطة، أو موقع ذكاء اصطناعي مصغّر.", list: ["حالة استخدام واحدة", "تسليم خلال 3 أسابيع", "تدريب مشمول", "30 يوماً من الدعم"] },
        { featured: true, badge: "الأكثر طلباً", name: "النمو", price: "ابتداءً من 25 000 درهم", desc: "حزمة كاملة من الأتمتة + روبوت محادثة + ذكاء اصطناعي خفيف، منشورة ومدمجة مع أدواتك.", list: ["من 3 إلى 5 حالات استخدام", "تكاملات CRM / ERP", "لوحة عائد الاستثمار", "3 أشهر من الدعم"] },
        { name: "السيادية", price: "حسب الطلب", desc: "ذكاء اصطناعي محلي كامل على بنيتك التحتية، ضبط دقيق، أمان متقدم، مرافقة طويلة الأمد.", list: ["نماذج منشورة on-premise", "ضبط دقيق حسب القطاع", "امتثال GDPR / ISO", "متابعة شهرية مخصصة"] },
      ],
    },
    cta: { title: "لديك فكرة؟ لنتحدث.", text: "تدقيق مجاني لمدة 30 دقيقة لتأطير مشروعك وتحديد الأتمتة ذات العائد المرتفع.", btn: "ابدأ الآن ›" },
  },
  solutions: {
    hero: { tag: "حلول الذكاء الاصطناعي", titleHtml: `حالات استخدام <span class="text-grad">ملموسة ومنشورة</span>`, sub: "لأن الحل الجيد للذكاء الاصطناعي يحل مشكلة محددة. إليك أكثر الاستخدامات طلباً من عملائنا — كل منها قابل للنشر في بضعة أسابيع." },
    intro: { tag: "حالات استخدام الذكاء الاصطناعي", titleHtml: `ثماني حلول <span class="text-grad">جاهزة للنشر</span>`, text: "كل بطاقة أدناه تقابل حالة استخدام مثبتة. انقر لتخصيص طلبك حسب احتياجاتك الدقيقة." },
    cardCta: "اطلب عرض سعر ›",
    cards: [
      { icon: "📚", title: "مساعد المستندات (RAG)", desc: "يستعلم موظفوك بلغة طبيعية عن جميع مستنداتك الداخلية: الإجراءات، العقود، المعايير، الأرشيف. أجوبة موثَّقة المصدر في ثوانٍ.", list: ["فهرسة Word وPDF وExcel والبريد", "أجوبة مع استشهادات", "صلاحيات لكل مستخدم", "نشر محلي أو سحابة خاصة"] },
      { icon: "🧾", title: "OCR واستخراج المستندات", desc: "استخراج تلقائي للبيانات من الفواتير وأوامر الشراء والعقود والوصفات — تُحقن مباشرة في ERP أو محاسبتك.", list: ["دقة +95٪ على الفواتير FR/AR", "تحقق بشري عند الشك", "تكامل Sage وOdoo وExcel", "أرشفة تلقائية"] },
      { icon: "📱", title: "روبوت واتساب تجاري", desc: "وكيل ذكاء اصطناعي متاح على مدار الساعة على واتساب لتأهيل عملائك المحتملين، والإجابة عن الأسئلة الشائعة، والتحويل إلى البشر عند الحاجة.", list: ["متعدد اللغات (FR / AR / دارجة / EN)", "كتالوج منتجات ودفع", "مزامنة CRM لحظية", "إحصاءات التحويل"] },
      { icon: "📊", title: "تقارير مؤتمتة", desc: "لوحات تُبنى ذاتياً من بياناتك. لا مزيد من النسخ واللصق في Excel: تصل التقارير مباشرة عبر البريد أو Slack.", list: ["ربط Google Sheets وSQL وAPI", "تنبيهات ذكية", "ملخصات تلقائية بالذكاء الاصطناعي", "إرسال مجدول"] },
      { icon: "📞", title: "صوت بالذكاء الاصطناعي والهاتف", desc: "مقسم هاتفي بالذكاء الاصطناعي، تفريغ المكالمات، ملخصات تلقائية. لا يفوّت مندوبوك أي معلومة.", list: ["مقسم ذكي (IVR بالذكاء الاصطناعي)", "تفريغ FR / AR", "ملخص مكالمة تلقائي", "كشف المشاعر"] },
      { icon: "👁", title: "الرؤية الصناعية", desc: "مراقبة الجودة، العد، قراءة اللوحات، كشف الشذوذ. يحلل الذكاء الاصطناعي تدفقات الفيديو لحظياً، دون سحابة.", list: ["إعادة استخدام كاميرات IP الحالية", "استدلال محلي لحظي", "تنبيهات وتقارير", "GDPR by design"] },
      { icon: "📅", title: "حجز مواعيد ذكي", desc: "يحجز عملاؤك بأنفسهم عبر واتساب أو الويب، ويدير الذكاء الاصطناعي تعارضات الجدول، ويرسل التذكيرات، ويحصّل المدفوعات.", list: ["مزامنة Google / Outlook", "تذكيرات SMS / واتساب", "إلغاء وإعادة جدولة", "دفع إلكتروني مدمج"] },
      { icon: "🔍", title: "الرصد وتوليد المحتوى", desc: "رصد تنافسي آلي، توليد منشورات، بطاقات منتجات، أوصاف SEO — مكيَّفة مع نبرة علامتك.", list: ["scraping ورصد", "توليد متعدد الصيغ", "تكييف نبرة الصوت", "تحقق قبل النشر"] },
    ],
    realcases: {
      tag: "حالات واقعية", titleHtml: `حلول <span class="text-grad">تعمل في الإنتاج</span>`, intro: "بعض آراء العملاء الذين يستخدمون هذه الحلول يومياً.",
      items: [
        { text: "يعالج OCR الفواتير من NAXA 1200 فاتورة شهرياً دون تدخل. استعاد محاسبنا 3 أيام شهرياً — وأعدنا توجيه وقته إلى التحليل المالي.", initials: "YA", name: "Yassine A.", role: "مدير إداري", company: "الدار البيضاء" },
        { text: "يجيب مساعد RAG للمستندات لدينا في 3 ثوانٍ عن أسئلة كانت تتطلب 30 دقيقة من البحث. يستخدمه محامو المكتب كل يوم.", initials: "FB", name: "Fatima B.", role: "مكتب قانوني", company: "الرباط" },
        { text: "يدير الصوت بالذكاء الاصطناعي 70٪ من المكالمات الواردة، ويؤهّل المرضى ويحجز المواعيد. أصبح مقسمنا الهاتفي غير مرئي — ومرضانا راضون.", initials: "HM", name: "Dr. Hicham M.", role: "مركز طبي", company: "طنجة" },
      ],
    },
    faq: {
      tag: "أسئلة الحلول", titleHtml: `كل ما يجب <span class="text-grad">معرفته</span> قبل البدء`,
      items: [
        { q: "كم من الوقت لأول نموذج أولي؟", a: "بين أسبوعين وثلاثة لـ POC عملي على بياناتك الحقيقية. يتيح لك ذلك التحقق الملموس من القيمة قبل أي التزام طويل. ثم يستغرق الإطلاق الكامل في الإنتاج من 4 إلى 8 أسابيع حسب التعقيد." },
        { q: "هل حلولكم متوافقة مع أدواتي الحالية؟", a: "نعم. نتكامل أصلياً مع HubSpot وSalesforce وOdoo وSage وPipedrive وGoogle Workspace وMicrosoft 365 وWhatsApp Business، وأي أداة تكشف API. وللأدوات بدون API، نطوّر موصِّلات مخصصة." },
        { q: "هل تبقى بياناتي لديّ فعلاً؟", a: "نعم — إنها بصمتنا. تعمل نماذج الذكاء الاصطناعي على خوادمك أو في سحابتك الخاصة. لا تمر أي بيانات عبر OpenAI أو Google أو أي خدمة خارجية. وهذا ما يجعل حلولنا مناسبة للقطاعات المنظَّمة: الصحة، القانون، المالية، القطاع العام." },
        { q: "ما مدى استقلاليتي بعد التسليم؟", a: "كاملة إن أردت. يتم تدريب فرقك، وكل حل موثَّق، والكود ملك لك. يمكنك تطوير الحل داخلياً، أو مع مستقل، أو الاستمرار معنا عبر باقة شهرية للدعم والتطوير." },
        { q: "هل يمكن إضافة حالات استخدام أخرى لاحقاً؟", a: "بالتأكيد. بمجرد أن تكون بنية الذكاء الاصطناعي جاهزة (نماذج، قاعدة متجهات، أتمتة)، تستغرق إضافة حالة استخدام جديدة عادة من أسبوع إلى أسبوعين، بتكلفة هامشية. هذا هو الأثر الرافع الذي توفره منصة مصممة جيداً منذ البداية." },
        { q: "ما الميزانية المتوقعة لحل كامل؟", a: "تبدأ حالة استخدام بسيطة حول 8 000 درهم. ويقع الحل المتكامل ببنية ذكاء اصطناعي محلي (نماذج، vector DB، أتمتة) عادة بين 25 000 و80 000 درهم حسب التعقيد. نقدّم دائماً تدقيقاً مجانياً وPOC بتكلفة محكومة قبل أي التزام طويل." },
      ],
    },
    cta: { title: "حالة استخدامك غير مدرجة؟", text: "نصمم أيضاً حلول ذكاء اصطناعي مخصصة. صِف لنا حاجتك — نعود إليك بمقاربة خلال 48 ساعة.", btn: "ناقش مشروعي ›" },
    breadcrumbName: "حلول الذكاء الاصطناعي",
  },
  about: {
    hero: { tag: "من نحن", titleHtml: `وكالة مصمَّمة <span class="text-grad">للشركات الطموحة</span>`, sub: "وُلدت NAXA من قناعة بسيطة: الذكاء الاصطناعي يجب ألا يكون منتجاً نستهلكه، بل أداة نتقنها. نساعد الشركات المغربية على استعادة التحكم في تحولها الرقمي." },
    mission: {
      tag: "مهمتنا", titleHtml: `دمقرطة <span class="text-grad">الذكاء الاصطناعي السيادي</span>`,
      paras: ["ترسل شركات كثيرة بياناتها الأكثر حساسية إلى نماذج سحابية أجنبية، دون رؤية لما يحدث لها. نعتقد أنه من الممكن — والضروري — بناء حلول ذكاء اصطناعي قوية مع الاحتفاظ ببياناتك لديك.", "مهمتنا: تحويل هذه القناعة إلى واقع تشغيلي لك."],
      distinguishTitle: "ما يميزنا",
      distinguishList: ["نهج الذكاء الاصطناعي المحلي افتراضياً", "مصدر مفتوح بدل SaaS المغلق", "POC سريعة، عائد استثمار مثبت", "توثيق وتدريب الفرق", "دعم محلي، بالفرنسية"],
    },
    values: {
      tag: "قيمنا", titleHtml: `أربعة <span class="text-grad">مبادئ غير قابلة للتفاوض</span>`,
      items: [
        { icon: "🛡", title: "السيادة", desc: "بياناتك هي أثمن أصولك. تبقى لديك، وانتهى." },
        { icon: "🎯", title: "عائد استثمار قابل للقياس", desc: "كل مشروع مؤطَّر بمؤشرات أداء واضحة. لا وعود غامضة، بل نتائج." },
        { icon: "🤝", title: "الشفافية", desc: "كود موثَّق، خيارات تقنية موضَّحة، أسعار معلنة مسبقاً." },
        { icon: "🚀", title: "البراغماتية", desc: "نبدأ صغاراً، نثبت القيمة، ثم نتوسّع. لا انفجار كبير." },
      ],
    },
    stats: [
      { num: 40, suffix: "+", label: "مشاريع مُسلَّمة" },
      { num: 15, suffix: "+", label: "قطاعات مغطّاة" },
      { num: 98, suffix: "%", label: "عملاء راضون" },
      { num: 3, suffix: "x", label: "متوسط العائد الملحوظ" },
    ],
    team: {
      tag: "الفريق", titleHtml: `فريق <span class="text-grad">متعدد التخصصات</span>`, intro: "مهندسو ذكاء اصطناعي، مطوّرون full-stack، مصممو تجربة مستخدم، ومستشارون مهنيون — تحت سقف واحد للتسليم بسرعة وجودة.",
      members: [
        { initials: "KE", name: "Karim El M.", role: "مؤسس · الذكاء الاصطناعي والاستراتيجية" },
        { initials: "CH", name: "Chaymae H.", role: "مديرة التصميم وتجربة المستخدم" },
        { initials: "YA", name: "Younes A.", role: "مهندس تعلّم آلي" },
        { initials: "SO", name: "Salma O.", role: "الأتمتة وروبوتات المحادثة" },
      ],
    },
    cta: { title: "لنعمل معاً", text: "سواء كان لديك مشروع محدد أو مجرد فضول، نأخذ الوقت لمناقشته بجدية.", btn: "تواصل معنا ›" },
  },
  contact: {
    hero: { tag: "اتصل بنا", titleHtml: `لنتحدث عن <span class="text-grad">مشروعك</span>`, sub: "صِف لنا حاجتك في بضعة أسطر — نعود إليك خلال 24 ساعة بتحليل أولي مجاني." },
    info: {
      title: "تواصل معنا مباشرة", text: "نرد خلال ساعات قليلة، من الإثنين إلى السبت.",
      phoneLabel: "الهاتف", whatsappLabel: "واتساب", whatsappLink: "تحدّث مباشرة",
      emailLabel: "البريد الإلكتروني", locationLabel: "الموقع", locationValue: "المغرب — تدخلات عن بُعد وفي الموقع",
      hoursLabel: "ساعات العمل", hoursValue: "الإثنين–السبت · 9:00 — 19:00",
    },
    form: {
      title: "ابدأ مشروعاً", sub: "رد مضمون خلال 24 ساعة عمل.",
      nom: "الاسم الكامل *", nomPh: "اسمك",
      email: "البريد الإلكتروني *", emailPh: "you@company.ma",
      entreprise: "الشركة", entreprisePh: "اسم شركتك",
      telephone: "الهاتف", telephonePh: "06 XX XX XX XX",
      service: "ما الخدمة التي تهمك؟ *", serviceDefault: "— اختر —",
      serviceOptions: ["ذكاء اصطناعي محلي (on-premise)", "أتمتة الأعمال", "روبوت واتساب / ويب", "إبداع رقمي (موقع، هوية)", "تدقيق واستشارة", "أخرى / لست متأكداً بعد"],
      message: "صِف حاجتك *", messagePh: "بضعة أسطر عن نشاطك، حاجتك، والموعد المثالي لديك...",
      submit: "أرسل طلبي ›", note: "بإرسال هذا النموذج، ستتم إعادة توجيهك إلى واتساب لإتمام التواصل.",
    },
  },
  merci: { tag: "تم استلام الطلب", titleHtml: `شكراً على <span class="text-grad">رسالتك</span>`, sub: "يعاود فريقنا التواصل معك خلال 24 ساعة عمل. لمحادثة فورية، تواصل معنا عبر واتساب.", btnWa: "💬 المتابعة على واتساب", btnHome: "العودة إلى الرئيسية" },
  nf: { tag: "خطأ 404", titleHtml: `الصفحة <span class="text-grad">غير موجودة</span>`, sub: "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.", btnHome: "العودة إلى الرئيسية", btnContact: "اتصل بنا" },
};

module.exports = { fr, en, ar };
